Merge translated documents into main document (F)
CppKorea/CppCoreGuidelines pull request #109
Opened 2016-12-31 07:59 UTC by jongheeyun

2017-01-01 13:08 UTC, utilForever requested changes
안녕하세요, 우선 번역 작업을 해주셔서 감사드립니다.
수정해야되는 부분이 있어서 안내드립니다.

함수 → F(Functions): 함수
함수인자 → 함수 인자
가져야하고 → 가져야 하고
인자와 결과값의 관계가 명확하게 기술되어야한다 → 인자와 결과값의 관계를 명확하게 기술해야 한다.
해야하고 → 해야 하고
함수 정의 규칙들 → 함수 정의 규칙
F.1: "패키지"란 고심끝에 이름지어진 함수처럼 의미있는 기능들의 모음 → F.1: 의미있는 동작들을 모아서 심사숙고해 함수 이름을 지어라
파라미터 전달 표현 규칙들 → 매개 변수 전달 표현 규칙
파라미터 전달 의미론적 규칙들 → 매개 변수 의미론적 규칙
값 반환 의미론적 규칙들 → 값 반환 의미론적 규칙
그 밖에 함수 규칙들 → 기타 함수 규칙
에러 → 오류
나쁜 예 → 나쁜 예제
에러 메시지 → 오류 메시지

(p.s. Subsections 폴더를 보시면 "F - Functions.md"라는 파일이 있습니다. 여기에 함수 부분이 1차 번역되어 있는데, 이 부분을 참고하셔서 번역 수정을 해주셔도 되겠습니다.)

2017-01-05 15:44 UTC, jongheeyun commented
리뷰의견 주셔서 감사합니다. 수정해서 다시 등록하겠습니다.

2017-01-05 15:48 UTC, jongheeyun commented
의견주셔서 감사합니다. 패치를 다시 등록하였습니다. (#3)

2017-01-09 04:04 UTC, utilForever approved these changes
고쳐야 할 몇 가지 사소한 맞춤법이 보이긴 합니다만, 큰 맥락에서는 이상이 없기에 리뷰 통과하고 머지하도록 하겠습니다. 고생하셨습니다.

2017-01-09 04:04 UTC, merged