Add appendix D
CppKorea/CppCoreGuidelines pull request #111
Opened 2017-10-06 12:48 UTC by jongheeyun

원문 October 5, 2017 버전의 appendix D를 추가 하였습니다.

2017-10-08 12:58 UTC, utilForever requested changes
고생하셨습니다. 몇 가지 의견이 있어서 달아뒀으니 확인하시고 답변 부탁드립니다.

2017-10-08 12:58 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +C++ 핵심 가이드라인을 적용하는데 직접적으로 도움을 주는 도구들을 이 섹션에 나열 하였습니다. 하지만 좋은 C++ 코드를 작성하는데 도움을 주는 도구들의 완벽한 모음을 만드려는 의도는 아닙니다. C++ 핵심 가이드라인을 지원하는 도구라면 이 문서에 링크를 남겨주세요. 문서에 기록 될 후보가 됩니다.
직역한 느낌이 많이 납니다. 예를 들어, 첫 문장은 다음과 같이 번역하는게 더 좋아 보입니다.
``` 이 절에는 C++ 핵심 가이드라인을 적용하는데 도움을 주는 도구들을 소개합니다. ```
나머지 문장에서도 직역한 느낌이 많이 나니, 한글 문장으로 읽었을 때 어색한 부분은 고쳐주시면 좋겠습니다.

2017-10-08 12:58 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +Clang-tidy는 C++ 핵심 가이드라인을 강조하는 규칙들을 포함하고 있습니다. 이 규칙들은 `cppcoreguidelines-*` 형태로 이름이 지어졌습니다.
```enforce```는 ```집행하다, 강요하다```라는 뜻을 갖고 있습니다. 따라서 다음 문장은 ```Clang-tidy는 C++ 핵심 가이드라인을 강제하는 규칙들을 포함하고 있습니다.```로 해석하는게 맞지 않을까 생각합니다.

2017-10-08 12:58 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +마이크로소프트 컴파일러의 코드 분석기는 C++ 핵심 가이드라인을 따를 수 있도록 강조해주는 규칙들을 포함하고 있습니다.
여기도 위와 마찬가지입니다.

2017-10-08 19:53 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +C++ 핵심 가이드라인을 적용하는데 직접적으로 도움을 주는 도구들을 이 섹션에 나열 하였습니다. 하지만 좋은 C++ 코드를 작성하는데 도움을 주는 도구들의 완벽한 모음을 만드려는 의도는 아닙니다. C++ 핵심 가이드라인을 지원하는 도구라면 이 문서에 링크를 남겨주세요. 문서에 기록 될 후보가 됩니다.
저도 기계적인 느낌이 많이 나서 고민이었습니다.
자연스러운 문장을 찾아보겠습니다.

2017-10-08 19:59 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +Clang-tidy는 C++ 핵심 가이드라인을 강조하는 규칙들을 포함하고 있습니다. 이 규칙들은 `cppcoreguidelines-*` 형태로 이름이 지어졌습니다.
"강제"와 "강조" 사이에서 고민하다가 "강제"는 부정적인 어감이 있어서 "강조"를 선택했습니다.
하지만 좋은 의도의 "강제"도 있다는 생각이 듭니다. 수정하겠습니다.

2017-10-09 01:04 UTC, utilForever approved these changes
피드백 확인했습니다. 고생하셨습니다.

2017-10-09 01:04 UTC, merged