Update concurrency section (CP)
CppKorea/CppCoreGuidelines pull request #114
Opened 2017-10-11 14:01 UTC by jongheeyun

- update CP section with latest version (Oct. 5, 2017)
 - translate intro part

2017-10-14 07:05 UTC, utilForever requested changes
조금 늦게 살펴봤네요. 고생하셨습니다.
띄워쓰기가 잘못된 부분이나 번역이 누락된 경우가 있어서 리뷰로 남겨뒀습니다. 그리고 매끄럽게 번역하면 좋을 부분들도 리뷰로 남겨뒀습니다. 확인하신 뒤에, 필요한 부분은 수정해주시면 감사하겠습니다.

2017-10-14 07:05 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +우리는 컴퓨터가 동시에 많은 작업을 하기를 원하고, 그렇게 동작하는것 처럼 보이게 만들기도 한다.
띄워쓰기가 잘못되었네요. ```동작하는것 처럼``` -> ```동작하는 것처럼```

2017-10-14 07:05 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +단일 프로세서만 사용하여 많은 이벤트를 기다리거나, 많은 데이터 스트림을 동시에 처리하거나 또는 많은 하드웨어 기능을 활용하려는 경우 등 이유는 다양하다.
좀 더 매끄럽게 바꿀 수 있을 것 같습니다.
```이렇게 하는 이유는 다양한데, '단일 프로세서만을 사용해 많은 이벤트를 기다리게 만들기 위해', '많은 데이터 스트림을 동시에 처리하기 위해', 또는 '많은 하드웨어 기능을 활용하기 위해' 등이 있다.```

2017-10-14 07:05 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +스레드는 동시적이거나 병렬적인 프로그래밍의 핵심이다. 스레드 덕분에 동일한 메모리를 공유하면서 프로그램의 여러 인스턴스를 독립적으로 실행할 수 있다.
좀 더 매끄럽게 바꿀 수 있을 것 같습니다.
```동시성 프로그래밍과 병렬 프로그래밍의 핵심은 스레드다.```

2017-10-14 07:05 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +동시적인 프로그래밍은 여러 가지 이유로 까다롭다. 대표적으로 한 스레드에서 데이터를 읽는 동안 다른 스레드에서 같은 데이터를 덮어쓸 때 발생하는 비정의 동작(undefined behavior)이 있다. 기존의 단일 스레드 코드를 동시적인 코드로 변경하는 것은 `std::async` 나`std::thread`를 추가하는 것만으로 쉽게 끝날 수도 있지만, 동
좀 더 매끄럽게 바꿀 수 있을 것 같습니다.
```동시성 프로그래밍은 여러 가지 이유로 인해 작업하기 까다롭다. 대표적으로 하나의 스레드에서 데이터를 읽는 동안 다른 스레드에서 같은 데이터를 덮어쓸 경우에 발생하는 정의되지 않은 동작(undefined behavior)이 있다. 기존의 단일 스레드 코드를 동시성 코드로 변경하기 위해서는 `std::async`나 `std::thread`를 추가하면 쉽게 해결되지만, 동시성이 고려되지 않은 코드라면 코드 전체를 다시 작성해야 할 수도 있다.```

2017-10-14 07:05 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +이 문서의 동시성/병렬성 규칙은 3가지 목표를 가지고 설계되었다.
좀 더 매끄럽게 바꿀 수 있을 것 같습니다.
```이 문서의 동시성/병렬성 규칙은 3가지 목표를 염두에 두고 설계했다.```

2017-10-14 07:05 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +* 동시성, 병렬성 기법이 기대했던 성능을 보이지 않을 때 무엇을 해야하는지 지침을 제공한다.
좀 더 매끄럽게 바꿀 수 있을 것 같습니다.
```동시성, 병렬성을 사용해 원하는 성능을 얻을 수 없을 경우, 무엇을 해야하는지에 대한 지침을 제공한다.```

2017-10-14 07:05 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +C++이 제공하는 동시성 기법은 지금도 계속 발전하고 있다. 특히 중요한 동시성 연산들이 C++11에 많이 소개되었고, C++14에서는 그것들을 개선하여 C++로 동시성 프로그램을 구현하는것이 즐겁고 더 쉬워지기까지 했다.
좀 더 매끄럽게 바꿀 수 있을 것 같습니다.
```C++이 제공하는 동시성은 지금도 계속 발전하고 있다. 특히 중요한 동시성 기능들이 C++11에 많이 도입되었고, C++14에서는 이 기능들을 개선했다. 그 결과, C++로 동시성 프로그램을 더욱 쉽고 재밌게 만들 수 있게 되었다.```

2017-10-14 07:05 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +일부 스레드관련 라이브러리의 사용지침은 시간이 지나면서 가치있는 방향으로 변화가 있을 것이다.
띄워쓰기가 잘못되었네요. ```스레드관련``` -> ```스레드 관련```, ```사용지침``` -> ```사용 지침```
좀 더 매끄럽게 바꿀 수 있을 것 같습니다.
```일부 스레드 관련 라이브러리의 사용 지침은 점차 가치있는 방향으로 변화할 것이다.```

2017-10-14 07:05 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +우선은 동시성에 덜 익숙한 사용자를 위한 규칙으로 시작할 것이니, 동시성 전문가라면 좀 더 기다려주길 바란다.
번역이 일부 누락되어 있습니다.
```우선은 동시성/병렬성에 익숙하지 않은 사용자들을 위한 규칙으로 시작하려고 한다. 전문가라면 좀 더 기다려주기 바란다.```

2017-10-14 07:05 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +이 문서에 기여하는 것은 언제나 환영한다. 하지만 동시성에 익숙하지 않은 개발자들이 정확하고, 빠른 동시적인 프로그램을 작성할 수 있도록 배려해주길 바란다.
좀 더 매끄럽게 바꿀 수 있을 것 같습니다.
```문서에 대한 기여는 환영하지만, 올바른 동작을 하며 속도가 빠른 동시성 프로그램을 만들기 위해 고군분투하고 있는 대다수의 프로그래머를 배려해주길 바란다.```

2017-10-16 13:24 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +우리는 컴퓨터가 동시에 많은 작업을 하기를 원하고, 그렇게 동작하는것 처럼 보이게 만들기도 한다.
네이버 맞춤법 검사기로 확인해서 수정하였습니다.

2017-10-16 13:24 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +단일 프로세서만 사용하여 많은 이벤트를 기다리거나, 많은 데이터 스트림을 동시에 처리하거나 또는 많은 하드웨어 기능을 활용하려는 경우 등 이유는 다양하다.
수정하였습니다.

2017-10-16 13:24 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +스레드는 동시적이거나 병렬적인 프로그래밍의 핵심이다. 스레드 덕분에 동일한 메모리를 공유하면서 프로그램의 여러 인스턴스를 독립적으로 실행할 수 있다.
수정하였습니다.

2017-10-16 13:24 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +동시적인 프로그래밍은 여러 가지 이유로 까다롭다. 대표적으로 한 스레드에서 데이터를 읽는 동안 다른 스레드에서 같은 데이터를 덮어쓸 때 발생하는 비정의 동작(undefined behavior)이 있다. 기존의 단일 스레드 코드를 동시적인 코드로 변경하는 것은 `std::async` 나`std::thread`를 추가하는 것만으로 쉽게 끝날 수도 있지만, 동
수정하였습니다.

2017-10-16 13:24 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +이 문서의 동시성/병렬성 규칙은 3가지 목표를 가지고 설계되었다.
수정하였습니다.

2017-10-16 13:24 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +* 동시성, 병렬성 기법이 기대했던 성능을 보이지 않을 때 무엇을 해야하는지 지침을 제공한다.
수정하였습니다.

2017-10-16 13:24 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +C++이 제공하는 동시성 기법은 지금도 계속 발전하고 있다. 특히 중요한 동시성 연산들이 C++11에 많이 소개되었고, C++14에서는 그것들을 개선하여 C++로 동시성 프로그램을 구현하는것이 즐겁고 더 쉬워지기까지 했다.
수정하였습니다.

2017-10-16 13:24 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +일부 스레드관련 라이브러리의 사용지침은 시간이 지나면서 가치있는 방향으로 변화가 있을 것이다.
수정하였습니다.

2017-10-16 13:24 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +이 문서에 기여하는 것은 언제나 환영한다. 하지만 동시성에 익숙하지 않은 개발자들이 정확하고, 빠른 동시적인 프로그램을 작성할 수 있도록 배려해주길 바란다.
수정하였습니다.
리뷰 감사드립니다.

2017-10-16 15:54 UTC, utilForever requested changes
리뷰 완료했습니다. 새로 작업한 부분에 대해서 피드백을 남겨놨으니 확인 부탁드립니다.
한 가지 부탁드리고 싶은게 있습니다. 한 번 리뷰를 통해 피드백이 끝나면, 수정 사항을 반영하고 머지한 후에 다음 작업을 풀 리퀘 해주시면 감사하겠습니다.

2017-10-16 15:54 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +참고 항목:
```참고할 만한 내용```

2017-10-16 15:54 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +* [CP.mess: 메세지 전달(Message passing)](#SScp-mess)
```메시지 전달```

2017-10-16 15:54 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +* [CP.free: 무잠금 프로그래밍(Lock-free programming)](#SScp-free)
락-프리라는 말을 더 많이 사용하기에 일단 원문 그대로 번역하는게 좋을 듯 합니다.
```락-프리 프로그래밍```

2017-10-16 15:54 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +##### 근거
```이유```

2017-10-16 15:54 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +##### 예
```예제```

2017-10-16 15:54 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +다중 스레드 환경에서는 절대 실행되지 않을 코드.
```다중 스레드 환경에서 절대로 실행되지 않는 코드.```

2017-10-16 15:54 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +##### 예외 사항
```예외```

2017-10-16 15:54 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +`cached_computation`함수는 단일 스레드 환경에선 완벽하게 동작하지만, 다중 스레드 환경에선 두 개의 `static` 변수가 데이터 경쟁에 빠져서 정의되지 않은 동작이 발생한다.
```cached_computation 함수는 단일 스레드 환경에서는 완벽하게 동작하지만, 다중 스레드 환경에서는 두 개의 static 변수가 데이터 경쟁에 빠져 정의되지 않은 동작을 한다.```

2017-10-16 15:54 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +동시성 프로그래밍을 지금하지 않는다고해서 앞으로도 계속 그럴거라고는 장담할 수 없다.
```지금 당장 동시성 프로그래밍을 하지 않는다고 해서, 앞으로도 계속 그럴거라고 장담할 수는 없다.```

2017-10-16 15:54 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +코드뿐 아니라 스레드를 사용한 라이브러리가 프로그램의 일부로 재활용된다는 사실은 단일 응용 프로그램보다는 라이브러리 코드에 더 적합한 원칙이다.
```코드는 재사용 될 수 있다.```
```스레드를 사용하는 라이브러리는 프로그램의 다른 부분에서 사용될 수 있다.```
```이로 인해 라이브러리 코드에는 이 규칙을 가장 시급히 적용해야 하며, 독립 실행 애플리케이션에는 시급하게 적용하지 않아도 된다.```

2017-10-16 15:54 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +특히나, 잘라서 붙여 넣기 덕분에 이런 코드 조각들은 예기치 못한 곳에서 불쑥 나타나기 때문에 주의해야 한다.
```그러나, 잘라내기 및 붙여넣기의 마법 덕분에 예기치 않은 곳에서 코드 조각이 나타날 수 있다.```

2017-10-16 15:54 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +* 단일 스레드 환경과 다중 스레드 환경을 위한 구현을 각각 제공한다.
```동시성 관련 문제를 호출자에게 위임하라.```
```static 변수를 thread_local으로 표시하라. (하지만 캐싱 효과는 줄어들 수 있다)```
```동시성 제어를 구현하라. 예를 들어, 두 static 변수를 static 락으로 보호하라. (하지만 성능이 저하될 수 있다)```
```호출자에게 캐시에 사용할 메모리를 제공해 메모리 할당과 동시성 관련 문제를 위임하라.```
```다중 스레드 환경에서 빌드되거나 실행되지 않도록 하라.```
```단일 스레드 환경과 다중 스레드 환경을 위한 구현을 각각 제공하라.```

2017-10-16 15:54 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +보통 그런 프로그램은 데이터 경쟁을 없애는데 많은 노력이 들어간다. 따라서, 다중 스레드 환경에 적합하지 않은 코드는 분명하게 제약 사항이 기술되어야 하고, 컴파일 또는 실행시간에 이 문제를 찾을 수 있는 메커니즘이 함께 사용되는 것이 이상적이다.
```보통 이런 프로그램은 데이터 경쟁을 없애는데 많은 노력이 든다. 따라서, 다중 스레드 환경에 적합하지 않은 코드는 제약 사항을 명확하게 기술해야 하고, 이상적으로는 컴파일 타임 또는 런타임에 버그를 조기에 발견할 수 있는 메커니즘이 있는게 좋다.```

2017-10-16 22:20 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +참고 항목:
In.struct 항목에 'See also'가 '참고 항목'으로 번역되어 있습니다.

2017-10-16 22:21 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +* [CP.mess: 메세지 전달(Message passing)](#SScp-mess)
수정하겠습니다.

2017-10-16 22:21 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +* [CP.free: 무잠금 프로그래밍(Lock-free programming)](#SScp-free)
수정하겠습니다.

2017-10-16 22:26 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +##### 근거
수정하겠습니다.

2017-10-16 22:27 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +코드뿐 아니라 스레드를 사용한 라이브러리가 프로그램의 일부로 재활용된다는 사실은 단일 응용 프로그램보다는 라이브러리 코드에 더 적합한 원칙이다.
수정하겠습니다.

2017-10-16 22:34 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +특히나, 잘라서 붙여 넣기 덕분에 이런 코드 조각들은 예기치 못한 곳에서 불쑥 나타나기 때문에 주의해야 한다.
수정하겠습니다.

2017-10-16 22:34 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +##### 예
수정하겠습니다.

2017-10-16 22:35 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +`cached_computation`함수는 단일 스레드 환경에선 완벽하게 동작하지만, 다중 스레드 환경에선 두 개의 `static` 변수가 데이터 경쟁에 빠져서 정의되지 않은 동작이 발생한다.
수정하겠습니다.

2017-10-16 22:38 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +* 단일 스레드 환경과 다중 스레드 환경을 위한 구현을 각각 제공한다.
수정하겠습니다.

2017-10-16 22:41 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +##### 예외 사항
수정하겠습니다.

2017-10-16 22:41 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +다중 스레드 환경에서는 절대 실행되지 않을 코드.
수정하겠습니다.

2017-10-16 22:41 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +보통 그런 프로그램은 데이터 경쟁을 없애는데 많은 노력이 들어간다. 따라서, 다중 스레드 환경에 적합하지 않은 코드는 분명하게 제약 사항이 기술되어야 하고, 컴파일 또는 실행시간에 이 문제를 찾을 수 있는 메커니즘이 함께 사용되는 것이 이상적이다.
수정하겠습니다.

2017-10-16 22:43 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +동시성 프로그래밍을 지금하지 않는다고해서 앞으로도 계속 그럴거라고는 장담할 수 없다.
수정하겠습니다.

2017-10-16 22:53 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +참고 항목:
문서에 '참고할 만한 내용'과 '참고 항목'이 섞여있습니다.
'참고할 만한 내용'이 더 적합한 번역이면 '참고 항목'을 '참고할 만한 내용'으로 변경하는 패치를 별도로 작성하겠습니다.

2017-10-17 13:27 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +참고 항목:
네, 그렇게 해주시면 감사하겠습니다.

2017-10-17 13:29 UTC, utilForever approved these changes
수정 내역 확인했습니다. 고생하셨습니다.

2017-10-17 13:29 UTC, merged