CP.2 항목 번역
CppKorea/CppCoreGuidelines pull request #116
Opened 2017-10-29 01:51 UTC by jongheeyun

2017-11-06 04:07 UTC, utilForever commented
저녁에 확인하겠습니다.

2017-11-12 14:19 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +데이터 경쟁을 피하지 못 하면, 제대로 동작한다고 보장할 수도 없고 분석하기 어려운 미묘한 오류들이 계속 발생한다.
```못 하면``` → ```못하면```
```보장할 수도 없고``` → ```보장할 수 없고```

2017-11-12 14:50 UTC, utilForever requested changes
안녕하세요, 리뷰가 늦어 죄송합니다.
고려했으면 하는 부분에 피드백을 달아뒀습니다.
참고하시고 고칠 부분은 고쳐주시고,
다른 의견이 있다면 답변을 달아주세요.
그리고 일부 문장은 번역을 다시 한 번 고려해주세요.
언제나 수고해주셔서 감사드립니다.

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +데이터 경쟁을 피하지 못 하면, 제대로 동작한다고 보장할 수도 없고 분석하기 어려운 미묘한 오류들이 계속 발생한다.
```못 하면``` → ```못하면```
```보장할 수도 없고``` → ```보장할 수 없고```

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +간단한 예로, 두 스레드가 동일한 객체를 동기화 없이 동시에 접근할 수 있고, 최소 한 스레드에서 쓰기(non-`const` 연산 사용)를 한다면, 데이터 경쟁 상태다.
```동기화 없이``` → ```동기화하지 않은 채```
```쓰기(non-`const` 연산 사용)를``` → ```(`const`가 아닌 작업을 수행하는) 쓰기 작업을 수행한다면```
```데이터 경쟁 상태다``` → ```데이터 경쟁 상태가 된다```

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +어떻게 동기화를 사용하고 데이터 경쟁을 없앨지 알려주는 좋은 책이 많이 있다. 꼭 참고하기 바란다.
```동기화를 사용해 데이터 경쟁을 제거하는 방법에 대해 더 자세한 정보는 동시성을 다루는 좋은 책을 참고하길 바란다.```

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +아래 아주 간단한 예를 보면,
```아래``` → ```아래에```

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +##### 나쁜 예,
```,``` 제거해주세요.

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +id를 증가시키는 부분에서 데이터 경쟁이 발생하는데, 아래와 같은 문제를 포함해서 여러가지 문제가 발생한다.
```포함해서``` → ```포함해```

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +일반적으로 지역 정적 변수는 데이터 경쟁을 발생시키는 원인이 된다.
```정적``` → ```static```

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +* 스레드 A가 `id`를 로드하고, 운영체제가 다른 스레드를 실행하려고 A를 중지시킨다. 그 사이 다른 스레드가 ID를 수백 개 생성한다. 그 후에 A는 다시 실행되고, A의 문맥에서는 `id`를 하나 증가시킨 값을 읽는다.
이 문장은 다시 한 번 생각해 주세요.

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +* 스레드 A와 B가 `id`를 로드하고 동시에 증가시킨다. 그 결과 두 스레드는 같은 ID값을 가진다.
```가진다``` → ```갖는다```

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +##### 나쁜 예,
```,``` 제거해주세요.

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +이 코드에서는, `buf`의 원소들에 대한 위험한 데이터 경쟁이 있다. (`sort`가 읽기와 쓰기를 수행한다).
```여기서 `buf`의 원소에 대해 (위험한) 데이터 경쟁이 있다 (`sort`는 읽기와 쓰기를 모두 수행할 것이다).```

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +이 코드는 스택 상의 데이터에서 발생하는 데이터 경쟁을 처리하고 있다.
이 문장은 다시 한 번 생각해 주세요.

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +* `static`변수 사용하지 않기
```static 변수를 사용하지 마라```

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +* 스택 상에서 값형식을 더 많이 사용하기 (포인터를 너무 많이 전달하지 말아라)
```스택 상에서 값 타입을 더 많이 사용하라 (그리고 포인터를 너무 많이 전달하지 말아라)```

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +* 불변형(상수형) 데이터 많이 사용하기 (리터럴, `constexpr`, `const`)
```불변 데이터(리터럴, `constexpr`, `const`)를 많이 사용하라```

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +* 전역 데이터 사용하지 않기
```전역 데이터를 사용하지 마라```

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +이 문제를 해결하기 위한 상업 및 오픈소스 도구가 있다. 하지만 해결책은 비용과 알아채지 못 한 문제점을 수반한다.
```못 한``` → ```못한```

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +정적 도구들은 오용탐지(false positive)를 하는 경우가 있고, 런타임 도두들은 비용이 많이 들어가는 문제가 있다.
```정적 도구는 거짓 양성(False Positive) 반응을 보이는 경우가 있고, 런타임 도구는 비용이 비싸다는 문제가 있다.```

2017-11-12 14:50 UTC, utilForever commented on CppCoreGuidelines - Korean.md
> +실제로, 더 나쁜 결과로 이어질 수도 있다: 생성된 코드를 살펴보면 주어진 값에 따라서 어디로 이동할지 알 수 있겠지만, 이는 보안에 위험요소다.
이 문단은 형식에 맞게 다시 정리해 주시고, 번역도 다시 한 번 생각해 주세요.

2017-11-13 13:37 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +데이터 경쟁을 피하지 못 하면, 제대로 동작한다고 보장할 수도 없고 분석하기 어려운 미묘한 오류들이 계속 발생한다.
수정하겠습니다.

2017-11-13 13:37 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +간단한 예로, 두 스레드가 동일한 객체를 동기화 없이 동시에 접근할 수 있고, 최소 한 스레드에서 쓰기(non-`const` 연산 사용)를 한다면, 데이터 경쟁 상태다.
수정하겠습니다.

2017-11-13 13:37 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +어떻게 동기화를 사용하고 데이터 경쟁을 없앨지 알려주는 좋은 책이 많이 있다. 꼭 참고하기 바란다.
수정하겠습니다.

2017-11-13 13:38 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +아래 아주 간단한 예를 보면,
수정하겠습니다.

2017-11-13 13:38 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +id를 증가시키는 부분에서 데이터 경쟁이 발생하는데, 아래와 같은 문제를 포함해서 여러가지 문제가 발생한다.
수정하겠습니다.

2017-11-13 13:38 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +* 스레드 A가 `id`를 로드하고, 운영체제가 다른 스레드를 실행하려고 A를 중지시킨다. 그 사이 다른 스레드가 ID를 수백 개 생성한다. 그 후에 A는 다시 실행되고, A의 문맥에서는 `id`를 하나 증가시킨 값을 읽는다.
수정하겠습니다.

2017-11-13 13:38 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +* 스레드 A와 B가 `id`를 로드하고 동시에 증가시킨다. 그 결과 두 스레드는 같은 ID값을 가진다.
수정하겠습니다.

2017-11-13 13:40 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +일반적으로 지역 정적 변수는 데이터 경쟁을 발생시키는 원인이 된다.
수정하겠습니다.

2017-11-13 13:41 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +이 코드에서는, `buf`의 원소들에 대한 위험한 데이터 경쟁이 있다. (`sort`가 읽기와 쓰기를 수행한다).
수정하겠습니다.

2017-11-13 13:42 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +이 코드는 스택 상의 데이터에서 발생하는 데이터 경쟁을 처리하고 있다.
수정하겠습니다.

2017-11-13 13:42 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +##### 나쁜 예,
수정하겠습니다.

2017-11-13 13:42 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +실제로, 더 나쁜 결과로 이어질 수도 있다: 생성된 코드를 살펴보면 주어진 값에 따라서 어디로 이동할지 알 수 있겠지만, 이는 보안에 위험요소다.
수정하겠습니다.

2017-11-13 13:44 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +* `static`변수 사용하지 않기
수정하겠습니다.

2017-11-13 13:44 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +* 스택 상에서 값형식을 더 많이 사용하기 (포인터를 너무 많이 전달하지 말아라)
수정하겠습니다.

2017-11-13 13:45 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +* 불변형(상수형) 데이터 많이 사용하기 (리터럴, `constexpr`, `const`)
수정하겠습니다.

2017-11-13 13:45 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +* 전역 데이터 사용하지 않기
수정하겠습니다.

2017-11-13 13:46 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +정적 도구들은 오용탐지(false positive)를 하는 경우가 있고, 런타임 도두들은 비용이 많이 들어가는 문제가 있다.
수정하겠습니다.

2017-11-13 13:46 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +이 문제를 해결하기 위한 상업 및 오픈소스 도구가 있다. 하지만 해결책은 비용과 알아채지 못 한 문제점을 수반한다.
수정하겠습니다.

2017-12-03 07:42 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +실제로, 더 나쁜 결과로 이어질 수도 있다: 생성된 코드를 살펴보면 주어진 값에 따라서 어디로 이동할지 알 수 있겠지만, 이는 보안에 위험요소다.
수정 하겠습니다.

2017-12-03 08:02 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +이 코드는 스택 상의 데이터에서 발생하는 데이터 경쟁을 처리하고 있다.
수정하겠습니다.

2017-12-03 08:09 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +이 코드는 스택 상의 데이터에서 발생하는 데이터 경쟁을 처리하고 있다.
"예제 코드는 스택 상 에서 발생하는 데이터 경쟁이다 -> 가까스로(어렵사리) 해결했다 -> 하지만 모든 데이터 경쟁이 이렇게 쉽게 발견되지는 않는다."는 의미로 번역하였습니다. 
spot을 (얼룩을)제거하다로 봐야할 지, (얼룩을)발견하다로 봐야할 지 고민하다가 "발견"으로 해석했습니다.

2017-12-03 08:11 UTC, jongheeyun commented on CppCoreGuidelines - Korean.md
> +실제로, 더 나쁜 결과로 이어질 수도 있다: 생성된 코드를 살펴보면 주어진 값에 따라서 어디로 이동할지 알 수 있겠지만, 이는 보안에 위험요소다.
"... by looking at the generated code you may be able to determine where `the stray jump` will go... " 에서  the stray jump를 어떻게 번역해야 할 지 몰라서 "표류 점프"로 직역하였습니다. 
더 나은 문구가 있으면 제안 부탁드립니다.

2017-12-29 14:42 UTC, jongheeyun commented
리뷰를 부탁드립니다.
감사합니다.

2017-12-29 14:54 UTC, utilForever commented
에고 확인이 늦었네요. 죄송합니다. 지금 바로 확인하겠습니다.

2017-12-29 14:54 UTC, utilForever approved these changes
수정 내역 확인했습니다. 수고하셨습니다.

2017-12-29 14:55 UTC, merged