Concurrency 번역 제출
CppKorea/CppCoreGuidelines pull request #132
Opened 2019-03-04 11:28 UTC by nochoco-lee

* Translation : CP.9

* Translation : CP.21 ~ CP.31

* Translation : CP.50 , CP.110

* Translation : CP.111

* Fix typos

2019-03-07 10:22 UTC, luncliff requested changes
제출해주셔서 감사합니다.
Enforcement부분 이외에는 그대로 적용하면 좋을 것 같습니다. 해당 부분에 대해 의견 부탁드립니다 :)

2019-03-11 11:01 UTC, nochoco-lee commented
> 제출해주셔서 감사합니다.
> Enforcement부분 이외에는 그대로 적용하면 좋을 것 같습니다. 해당 부분에 대해 의견 부탁드립니다 :)

리뷰 감사드립니다. 피드백 주신 내용 업데이트 하였습니다. 다른 수정이 더 필요한 부분 있으시면 말씀주세요^^

2019-03-11 11:09 UTC, luncliff approved these changes

2019-03-11 11:09 UTC, merged

2019-03-11 11:10 UTC, luncliff commented
기여해주셔서 감사드립니다 :)

2019-03-11 11:12 UTC, luncliff commented
@nochoco-lee ReadMe에 이름/URL을 어떻게 넣으면 좋을까요?
Issue #128 은 Close 해도 괜찮을지요? 

좀 더 변경할 사항이 필요하다면 새로 PR을 주셔도 좋을 것 같습니다.

2019-03-11 12:46 UTC, nochoco-lee commented
> @nochoco-lee ReadMe에 이름/URL을 어떻게 넣으면 좋을까요?
> Issue #128 은 Close 해도 괜찮을지요?
> 
> 좀 더 변경할 사항이 필요하다면 새로 PR을 주셔도 좋을 것 같습니다.

아 넵! Ji-hoon Lee [nochoco-lee](https://github.com/nochoco-lee/) 로 해주시면 감사하겠습니다, Issue #128 은 Close 하도록 하겠습니다 :)