P.12 번역
CppKorea/CppCoreGuidelines pull request #143
Opened 2019-06-21 08:08 UTC by snghojeong

2019-06-23 03:59 UTC, luncliff commented on sections/Philosophy.md
> +### <a name="Rp-tools"></a>P.12: 필요에 따라 지원 도구를 사용하라
필요라는 단어를 쓴 점이 좋은 것 같습니다. "필요에 맞게"는 어떠신지요?

2019-06-23 04:01 UTC, luncliff commented on sections/Philosophy.md
> +정적 분석기를 실행하여 코드가 원하는 지침을 따르는 지 확인하라.
나중을 위해 영단어를 함께 표기하면 좋을 것 같습니다.  
지침(guideline)

2019-06-23 04:01 UTC, luncliff commented on sections/Philosophy.md
> +* [동시설 도구들](#Rconc-tools)
오타 발견!

2019-06-23 04:02 UTC, luncliff requested changes
오타만 수정해주시면 괜찮을 것 같습니다. 후속 commit을 하실 예정이시라면 바로 merge 하지 않고 PR을 계속 열어두겠습니다.

2019-06-23 05:08 UTC, luncliff commented
@snghojeong 님, #140, #142 가 Merge되었으므로 ReadMe에 이름을 올려야 하는데, 추가 commit에서 ReadMe 쪽에도 프로필 링크 추가를 부탁드리겠습니다. :D

2019-06-24 02:02 UTC, snghojeong commented on sections/Philosophy.md
> +### <a name="Rp-tools"></a>P.12: 필요에 따라 지원 도구를 사용하라
좋은 리뷰에 감사드립니다. 번역문을 수정했습니다.
다음 커밋을 참고 해 주세요: https://github.com/CppKorea/CppCoreGuidelines/pull/143/commits/81b1194d918543242ca28a301f7709df10afa73a

2019-06-24 02:03 UTC, snghojeong commented on sections/Philosophy.md
> +정적 분석기를 실행하여 코드가 원하는 지침을 따르는 지 확인하라.
좋은 리뷰에 감사드립니다. 영문을 병행표기 했습니다.
다음 커밋을 참고해주세요: https://github.com/CppKorea/CppCoreGuidelines/pull/143/commits/f5aa06e4086febeec7f4eb1459aef08c5a304037

2019-06-24 02:04 UTC, luncliff approved these changes

2019-06-24 02:04 UTC, snghojeong commented on sections/Philosophy.md
> +* [동시설 도구들](#Rconc-tools)
앗! 찾아주셔서 감사합니다. 수정했습니다.
다음 커밋을 참고 해 주세요: https://github.com/CppKorea/CppCoreGuidelines/pull/143/commits/3bf6362d30a3a20cb0f47603bfa96655a8e93f28

2019-06-24 02:06 UTC, snghojeong commented
@luncliff 님, 프로필을 ReadMe.md에 추가했습니다.
브랜치의 이름이 적합치 않아서, trans-philosophy와 같은 이름으로 브랜치를 다시 만들고 PR을 열어두겠습니다.
해당 PR은 머지하고 P12브랜치는 지우겠습니다.

2019-06-24 02:07 UTC, merged