Update SL.md to include trivially-copyable section
CppKorea/CppCoreGuidelines pull request #153
Opened 2020-06-20 16:48 UTC by honggyukim

This patch applies the recent update of SL.md from the following commit.
https://github.com/isocpp/CppCoreGuidelines/commit/2fdc6960b47eb50221c6c1a84ff5bcc3570ec03e

It also applies a misc fix from the following commit.
https://github.com/isocpp/CppCoreGuidelines/commit/d636a1bc5fb10db062f022bf1a9a2b9b62e287e7

2020-06-27 14:47 UTC, utilForever requested changes
안녕하세요, 홍규님. 오랜만입니다. 저장소에 기여해주셔서 감사드립니다.
번역이 누락된 부분과 표현을 개선했으면 하는 부분들이 있어서 리뷰 남겨둡니다.
시간있을 때 확인해주시면 감사하겠습니다.

2020-06-27 14:47 UTC, utilForever commented on sections/SL.md
> +* [SL.con.4: trivially-copyable 하지 않은 객체들을 `memset` 이나 `memcpy` 의 인자로 사용하지 말라](#Rsl-copy)
```suggestion
* [SL.con.4: trivially-copyable하지 않은 객체들을 `memset`이나 `memcpy`의 인자로 사용하지 말라](#Rsl-copy)
```

2020-06-27 14:47 UTC, utilForever commented on sections/SL.md
> +### <a name="Rsl-copy"></a>SL.con.4: trivially-copyable 하지 않은 객체들을 `memset` 이나 `memcpy` 의 인자로 사용하지 말라.
```suggestion
### <a name="Rsl-copy"></a>SL.con.4: trivially-copyable하지 않은 객체들을 `memset`이나 `memcpy`의 인자로 사용하지 말라.
```

2020-06-27 14:47 UTC, utilForever commented on sections/SL.md
> +(w)memset, (w)memcpy, (w)memmove, 와 (w)memcmp 들도 유사한 문제가 있다.
```suggestion
(w)memset, (w)memcpy, (w)memmove, (w)memcmp도 유사한 문제가 있다.
```

2020-06-27 14:47 UTC, utilForever commented on sections/SL.md
> +Insted, define proper default initialization, copy, and comparison functions
```suggestion
대신 적절한 디폴트 초기화, 복사, 비교 함수를 정의하라.
```

2020-06-27 14:47 UTC, utilForever commented on sections/SL.md
> +> 역주: [trivially copyable](https://en.cppreference.com/w/cpp/named_req/TriviallyCopyable) 에 대한 더 자세한 정보는 링크에서 참고할 수 있으며 해당 타입이 trivially copyable 한 타입인지 여부는 [std::is_trivially_copyable](https://en.cp
```suggestion
> 역주: [trivially copyable](https://en.cppreference.com/w/cpp/named_req/TriviallyCopyable)의 자세한 정보는 링크에서 확인할 수 있으며 해당 타입이 trivially copyable한 타입인지 여부는 [std::is_trivially_copyable](https://en.cppreference.com/w/cpp/types/is_trivially_copyable)로 검사할 수 있다.
```

2020-06-27 14:47 UTC, utilForever commented on sections/SL.md
> +* trivially copyable 하지 않은 타입들에 대해서 그러한 함수들을 사용하면 지적하라.
```suggestion
* trivially copyable하지 않은 타입에 위에서 언급했던 함수들((w)memset, (w)memcpy, (w)memmove, (w)memcmp)을 사용하면 바로잡아라.
```

2020-06-27 14:47 UTC, utilForever commented
@luncliff 님, 시간있을 때 확인해주시면 감사하겠습니다.

2020-06-28 05:19 UTC, luncliff approved these changes

2020-07-12 08:09 UTC, honggyukim commented on sections/SL.md
> +Insted, define proper default initialization, copy, and comparison functions
제가 누락했던 곳이 있었군요. 찾아주셔서 감사합니다.

2020-07-12 08:10 UTC, honggyukim commented
안녕하세요. 찬호님, 답이 조금 늦었지만 리뷰해 주셔서 감사합니다. 말씀해주신 사항대로 수정해서 업데이트 다시 했습니다. 시간 되실때 확인 부탁 드립니다. 감사합니다.

2020-07-12 15:40 UTC, utilForever approved these changes
수정하신 부분 모두 확인했습니다. 기여해주셔서 감사합니다. 😄

2020-07-12 15:40 UTC, merged

2020-07-12 18:24 UTC, honggyukim commented
네. 감사합니다^^