Update R.14 contents
CppKorea/CppCoreGuidelines pull request #160
Opened 2023-05-08 00:52 UTC by gjxo12

Added content and examples for guideline R.14: Avoid [] parameters, prefer span.

2023-05-08 15:24 UTC, utilForever requested changes
Can you check my comments? Thanks.

2023-05-08 15:24 UTC, utilForever commented on sections/Resource.md
> +* [R.14: [] 파라미터는 피하고 span을 사용하라](#Rr-ap)
```suggestion
* [R.14: `[]` 매개변수 대신 `span`을 사용하라](#Rr-ap)
```

2023-05-08 15:24 UTC, utilForever commented on sections/Resource.md
> +### <a name="Rr-ap"></a>R.14: [] 파라미터는 피하고 span을 사용하라
```suggestion
### <a name="Rr-ap"></a>R.14: `[]` 매개변수 대신 `span`을 사용하라
```

2023-05-08 15:24 UTC, utilForever commented on sections/Resource.md
> +`[]` 파라미터 대신 `span`을 사용하라.
```suggestion
`[]` 매개변수 대신 `span`을 사용하라.
```

2023-05-10 00:36 UTC, gjxo12 commented
I checked that commit :) 
Thanks for pointing out what I missed :)

2023-05-10 01:12 UTC, utilForever approved these changes
LGTM now. Thanks for your work! 🏆

2023-05-10 01:27 UTC, luncliff approved these changes
Appreciate your contribution 👍 👍

2023-05-10 01:27 UTC, merged