Update Source File
CppKorea/CppCoreGuidelines pull request #161
Opened 2023-05-15 02:17 UTC by gjxo12

I found a document related to the static keyword while searching, and I noticed that it was missing some information from the SF guidelines. 
I went ahead and translated the document, but there may be some areas that require improvement, so I would appreciate it if you could review it.
- translate SF.11
- add guide SF.12 and translate except Note
- add example SF.21 / SF.22

Best regards
Hur.

2023-05-15 03:28 UTC, luncliff commented
Would you rebase with the master branch? #160 was squah merged, so there might be conflicts when you add more changes.

2023-05-15 03:47 UTC, luncliff requested changes
Same with the comment above

2023-05-15 04:00 UTC, gjxo12 commented
I mistakenly set the rebase to the other way, forced push. Is it correct that the commit shape of my forked branch looks like this?

2023-05-16 04:32 UTC, luncliff approved these changes
Sorry. Seems like the rebase was correct, but my web UI wasn't.
Appreciate time and contribution!

2023-05-16 04:33 UTC, luncliff commented
@utilForever , Would you approve the PR please?

2023-05-16 04:55 UTC, utilForever requested changes
Can you check my comments? Thanks.

2023-05-16 04:55 UTC, utilForever commented on sections/Source.md
> +헤더 파일은 모든 종속성을 포함해야한다. 상대 경로를 사용할때는 C++ 구현이(implementations) 의미가 다르기 때문에 주의해야한다.
```suggestion
헤더 파일은 모든 종속성을 포함해야 한다. 상대 경로를 사용할 때는 C++ 구현의 의미가 다르기 때문에 주의해야 한다.
```

2023-05-16 04:55 UTC, utilForever commented on sections/Source.md
> +테스트는 헤더 파일 자체가 컴파일되거나 헤더 파일만 포함한 cpp파일이 컴파일되는지 확인해야한다.
```suggestion
테스트는 헤더 파일 자체 또는 헤더 파일만 포함한 cpp 파일이 컴파일되는지 확인해야 한다.
```

2023-05-16 04:55 UTC, utilForever commented on sections/Source.md
> +* [SF.12: `#include`에서 상대 경로를 사용하는 파일에 대해서는 따옴표(`""`)를 사용하고 그 외에는 꺽쇠(`<>`)를 선호하라](#Rs-include-files)
```suggestion
* [SF.12: `#include`에서 상대 경로를 사용하는 파일은 큰따옴표(`""`)를 사용하고 그 외에는 홑화살괄호(`<>`)를 사용하라](#Rs-include-files)
```

2023-05-16 04:55 UTC, utilForever commented on sections/Source.md
> +### <a name="Rs-include-files"></a>SF.12: `#include`에서 상대 경로를 사용하는 파일에 대해서는 따옴표(`""`)를 사용하고 그 외에는 꺽쇠(`<>`)를 선호하라
```suggestion
### <a name="Rs-include-files"></a>SF.12: `#include`에서 상대 경로를 사용하는 파일은 큰따옴표(`""`)를 사용하고 그 외에는 홑화살괄호(`<>`)를 사용하라
```

2023-05-16 04:55 UTC, utilForever commented on sections/Source.md
> +이 [표준](http://eel.is/c++draft/cpp.include)은 컴파일러가 꺽쇠(`<>`)나 따옴표(`""`)문법을 사용하여 두가지 형태의 `#include`를 구현하는 유연성을 제공한다. 벤더(Vendors)들은 이를 활용하여 포함 경로를 지정하기 위해 다양한 검색 알고리즘과 방법을 사용한다.
```suggestion
이 [표준](http://eel.is/c++draft/cpp.include)은 컴파일러가 홑화살괄호(`<>`)나 큰따옴표(`""`) 문법을 사용해 두가지 형태의 `#include`를 구현하는 유연성을 제공한다. 벤더들은 이를 활용해 포함 경로를 지정하고자 다양한 검색 알고리즘과 방법을 사용한다.
```

2023-05-16 04:55 UTC, utilForever commented on sections/Source.md
> +그러나, 상대 경로에 존재하는 파일을 `#include`문(동일한 구성요소나 프로젝트에 있는)을 통해 포함하는 경우 따옴표(`""`)를 사용하고, 그 외의 경우(가능하면) 꺽쇠(`<>`)를 사용하는 것이 좋다.
```suggestion
그렇지만 상대 경로에 존재하는 파일을 (같은 구성 요소나 프로젝트에 있는) `#include`로 포함하는 경우에는 큰따옴표(`""`)를 사용하고 그 외의 경우에는 (가능하면) 홑화살괄호(`<>`)를 사용하는 게 좋다.
```

2023-05-16 04:55 UTC, utilForever commented on sections/Source.md
> +이는 파일을 포함하는 파일과 관련된 파일의 위치(locality) 또는 다른 검색 알고리즘이 필요한 경우에 대해 명확하게 알 수 있다. 헤더가 로컬 파일에서 포함되는지, 표준 라이브러리 헤더에서 포함되는지 아니면 다른 경로(예: 다른 라이브러리 또는 공통 세트)에서 헤더가 포함되는지를 빠르고 쉽게 결정할 수 있다.
```suggestion
이렇게 하면 `#include`로 포함한 파일들과 관련된 파일의 지역성이나 다른 검색 알고리즘이 필요한 시나리오를 명확히 파악할 수 있다. 헤더가 로컬 상대 경로 파일에서 포함되는지, 표준 라이브러리 헤더에서 포함되는지 아니면 다른 검색 경로(예를 들어, 다른 라이브러리의 헤더 또는 공통 `#include` 집합)에서 헤더가 포함되는지 한눈에 쉽게 파악할 수 있다.
```

2023-05-16 04:55 UTC, utilForever commented on sections/Source.md
> +테스트는 따옴표(`""`)구문을 사용하여 포함된 헤더가 꺽쇠(`<>`)구문을 사용하여 포함될수 있는지 확인해야 한다.
```suggestion
테스트는 큰따옴표(`""`) 구문을 사용해 포함된 헤더가 홑화살괄호(`<>`) 구문을 사용해 포함될 수 있는지 확인해야 한다.
```

2023-05-16 07:29 UTC, gjxo12 commented
Thanks for the detailed review.

I did a simple translation for the first time in my life, but it's not easy.

Korean is also difficult.

I have checked all comments and will apply them.

2023-05-16 07:33 UTC, GiyeonBang approved these changes

2023-05-16 07:34 UTC, GiyeonBang approved these changes

2023-05-16 07:37 UTC, GiyeonBang approved these changes

2023-05-16 07:38 UTC, GiyeonBang approved these changes

2023-05-16 07:38 UTC, GiyeonBang approved these changes

2023-05-16 07:39 UTC, GiyeonBang approved these changes

2023-05-16 07:39 UTC, GiyeonBang approved these changes

2023-05-16 09:47 UTC, utilForever approved these changes
LGTM now. Thanks! 🔖

2023-05-16 09:48 UTC, merged