Update Templates and generic programming
CppKorea/CppCoreGuidelines pull request #162
Opened 2023-06-15 03:24 UTC by gjxo12

While reading the documentation for that part, I checked once to see if it was the same as the original.

 Not all content has been completely corrected, but please review.

2023-06-17 12:12 UTC, utilForever requested changes
Can you check my comments? Thanks! 🔍

2023-06-17 12:12 UTC, utilForever commented on sections/Templates.md
> +컨셉(Concept)은 템플릿 인자들에 대한 요구사항을 지정하기 위한 C++ 20 기능이다.
```suggestion
컨셉(Concepts)은 템플릿 인자들에 대한 요구사항을 지정하기 위한 C++20 기능이다.
```

2023-06-17 12:12 UTC, utilForever commented on sections/Templates.md
> +분명, 컨셉을 정의하는 것은 컨셉 구현을 사용할 수 있는 (예컨대 c++20 혹은 그 이상) 코드에 유용할 것이다.
```suggestion
분명, 컨셉을 정의하는 것은 구현을 사용할 수 있는 (예를 들어, C++20 또는 그 이후) 코드에 유용할 것이다.
```

2023-06-17 12:12 UTC, utilForever commented on sections/Templates.md
>  ##### Enforcement
```suggestion
##### Note

템플릿 매개변수에 의존하지 않는 람다에도 적용된다.

##### Enforcement
```

2023-06-17 12:12 UTC, utilForever commented on sections/Templates.md
> +* 람다가 의존하지 않는 템플릿 매개변수가 있다면 지적한다
```suggestion
* 모든 템플릿 매개 변수에 의존하지 않는 멤버 타입을 표시하라.
* 모든 템플릿 매개 변수에 의존하지 않는 멤버 함수를 표시하라.
* 모든 템플릿 매개 변수에 의존하지 않는 람다나 변수 템플릿을 표시하라.
```

2023-06-19 01:48 UTC, gjxo12 commented
Thank you for your review.

I checked all commit.

Thanks for pointing out my mistake.

2023-06-19 01:54 UTC, utilForever approved these changes
I checked the changes. Thanks! 🍹

2023-06-19 02:09 UTC, GiyeonBang requested changes
Idiomatically, `컨셉` is used more common, but according to the National Institute of Korean Language(국립국어원), it is correct to write `컨셉` as `콘셉트`.
Or, since it is a proper noun, it is recommended not to describe it in Korean.
PS: I ask for opinions from other reviewers.

2023-06-19 02:14 UTC, GiyeonBang requested changes
Same as above.
`컨셉(Concepts)` --> `콘셉츠(Concepts)`
Or just `Concepts`

2023-06-19 03:34 UTC, luncliff approved these changes
Sorry for the late check. 

Would you check https://github.com/CppKorea/CppCoreGuidelines/pull/162#pullrequestreview-1485292285
?

Because `C++ 20 Concepts` is a unique name for the language feature.
I vote for just writing `Concepts` without Korean words.
But I respect the contributors' choice. Go ahead with your opinion.

2023-06-19 04:33 UTC, gjxo12 commented
I think just writing `Concepsts` without Korean words.

This expression looks concise and readable.

If the reviewers don't have any problems, I'd suggest modifing them with `Concepts`

By any chance, if I modify it, can I go through the process of editing -> commit -> push again?

2023-06-19 05:20 UTC, utilForever commented
> I think just writing `Concepsts` without Korean words.
> 
> This expression looks concise and readable.
> 
> If the reviewers don't have any problems, I'd suggest modifing them with `Concepts`
> 
> By any chance, if I modify it, can I go through the process of editing -> commit -> push again?

I agree. You can commit to this branch before PR is merged. 🗡️

2023-06-19 05:49 UTC, gjxo12 commented
> > I think just writing `Concepsts` without Korean words.
> > This expression looks concise and readable.
> > If the reviewers don't have any problems, I'd suggest modifing them with `Concepts`
> > By any chance, if I modify it, can I go through the process of editing -> commit -> push again?
> 
> I agree. You can commit to this branch before PR is merged. 🗡️

Ok. I refactored all words of "컨셉" to "Concepts".
If there are any other issues, i'll fix them again.

2023-06-19 07:34 UTC, GiyeonBang approved these changes

2023-06-19 08:34 UTC, merged