F.call: 매개변수 전달(Parameter passing) 번역 최신화
CppKorea/CppCoreGuidelines pull request #168
Opened 2024-03-10 20:06 UTC by jabdong4ny

F.call: 매개변수 전달(Parameter passing) 번역 최신화

2024-03-14 12:54 UTC, twoo0220 commented
특별히 수정해야될 부분 없어보입니다.
@luncliff 님 추가확인 부탁드리겠습니다.

2024-03-16 04:48 UTC, luncliff reviewed
첫번째 기여를 환영합니다. 아래의 제안들을 한번 검토해주시길 부탁드립니다. 👍 👍

2024-03-16 04:48 UTC, luncliff commented on sections/Functions.md
> +* [F.49: `return const T`는 사용하지 말아라](#Rf-return-const)
```suggestion
* [F.49: `const T`는 `return`에 사용하지 말아라](#Rf-return-const)
```

2024-03-16 04:48 UTC, luncliff commented on sections/Functions.md
> +* [F.49: `return const T`는 사용하지 말아라](#Rf-return-const)
```suggestion
* [F.49: `const T`는 함수의 반환 타입으로 사용하지 말아라](#Rf-return-const)
```

2024-03-16 04:48 UTC, luncliff commented on sections/Functions.md
> +`shared_ptr` 타입을 사용한 공유 소유권을 표현하려면 F.16-21 지침을 따르기보다는 [R.34](./References.md/#Rr-sharedptrparam-owner), [R.35](./References.md/#Rr-sharedptrparam) 및 [R.36](./References.md/#Rr-sharedptrparam-const)을
```suggestion
`shared_ptr` 타입을 사용한 공유 소유권을 표현하려면 F.16-21 지침을 따르기보다는 [R.34](./References.md/#Rr-sharedptrparam-owner), [R.35](./References.md/#Rr-sharedptrparam) 및 [R.36](./References.md/#Rr-sharedptrparam-const)을 참고하라.
```

가이드라인 전반적으로 권유보다는 "~하라" 어미를 사용하고 있어서 같이 맞추면 좋겠습니다.

2024-03-16 04:48 UTC, luncliff commented on sections/Functions.md
> +문자열 전달은 [String](#SS-string) 참고.
```suggestion
문자열 전달은 [String](./SL.md#SS-string) 참고.
```

2024-03-16 04:48 UTC, luncliff commented on sections/Functions.md
> +`shared_ptr` 유형을 사용하여 공유 소유권을 표현하려면 함수가 전달인자를 참조하는지 여부에 따라 [R.34](./References.md/#Rr-sharedptrparam-owner) 또는 [R.36](./References.md/#Rr-sharedptrparam-const)을 따르세요.
```suggestion
`shared_ptr` 타입을 사용하여 공유 소유권을 표현하려면 함수가 전달인자를 참조하는지 여부에 따라 [R.34](./References.md/#Rr-sharedptrparam-owner) 또는 [R.36](./References.md/#Rr-sharedptrparam-const)를 참고하라.
```

2024-03-16 04:48 UTC, luncliff commented on sections/Functions.md
> +일부 사용자 정의 및 표준 라이브러리 유형은 `span<T>`나 반복자와 같이 [복사 비용이 저렴](#Rf-in)하고 값으로 전달될 수 있지만, 변경 가능한(in-out) 참조 의미론을 가지고 있다:
```suggestion
일부 사용자 정의 및 표준 라이브러리 타입은 `span<T>`나 반복자와 같이 [복사 비용이 저렴](#Rf-in)하고 값으로 전달될 수 있지만, 변경 가능한(in-out) 참조 의미론(semantics)을 가지고 있다:
```

2024-03-16 04:48 UTC, luncliff commented on sections/Functions.md
> +일반적으로 모든 정적 제어 흐름 경로에서 전체 매개변수(또는 인자 묶음(pack), 또는 `...` 사용)를 정확히 한 번 전달합니다:
원문: Usually you forward the entire parameter (or parameter pack, using ...) exactly once on every static control flow path
```suggestion
일반적으로 모든 정적 제어 흐름 경로에서 전체 매개변수(또는 `...`을 사용하는 인자묶음(parameter pack))를 정확히 한 번 전달합니다:
```

2024-03-16 04:48 UTC, luncliff commented on sections/Functions.md
> +때로는 모든 정적 제어 흐름 경로에서 복합 매개 변수의 각 하위 개체를 한 번씩 전달할 수 있습니다:
```suggestion
때로는 모든 정적 제어 흐름 경로에서 복합 매개 변수의 각 하위 개체를 한 번씩 전달할 수 있다:
```

2024-03-16 04:48 UTC, luncliff commented on sections/Functions.md
> +* 모든 정적 경로에 대해 단 한번 `std::forward`하는 경우를 제외하고 `TP&&` 매개변수를 받는 함수를 지적한다. (`TP`는 템플릿 인자의 이름이다) 또는 `std::forward`을 한 번 이상 수행하지만 정적 경로마다 정확히 한 번씩 다른 데이터 멤버로 자격을 부여한다.
```suggestion
* 모든 정적 경로에 대해 단 한번 `std::forward`하는 경우를 제외하고 `TP&&` 매개변수를 받는 함수를 지적한다. (`TP`는 템플릿 인자의 이름이다) 또는 `std::forward`을 한 번 이상 수행하지만 정적 경로마다 정확히 한 번씩 다른 데이터 멤버로 자격을 부여한다.

> * Flag a function that takes a TP&& parameter (where TP is a template type parameter name) and does anything with it other than std::forwarding it exactly once on every static path, or std::forwarding it more than once but qualified with a different data member exactly once on every static path.
```

2024-03-16 04:48 UTC, luncliff commented on sections/Functions.md
> +반환 값은 그 자체로 문서가 필요하지 않고 "출력 전용"으로 사용된다. C++ 에서는 다수의 값을 반환할때는 튜플과 유사한 유형(`struct`, `array`, `tuple` 등)를 쓴다는 것을 기억하라, 호출한 지점에서 구조화된 바인딩(structured bindings)(C++17)을 추가로 편리하게 사용할 수 있다. 반환 값에 의미구조가 있다면 별
"유형" 보다는 "타입"을 사용하고, 문장을 분할하는 것을 제안합니다.
```suggestion
반환 값은 그 자체로 문서가 필요하지 않고 "출력 전용"으로 사용된다.
C++ 에서는 다수의 값을 반환할때는 튜플과 유사한 타입(`struct`, `array`, `tuple` 등)를 쓴다는 것을 기억하라,
호출한 지점에서 구조화된 바인딩(structured bindings)(C++17)을 추가로 편리하게 사용할 수 있다.
반환 값에 의미구조가 있다면 별도의 `struct` 타입을 사용하라.
그렇지 않다면 일반적인 코드에서는 (이름 없는) `tuple`이 유용하다.
```

2024-03-16 04:48 UTC, luncliff commented on sections/Functions.md
> +모던 C++에서는 의미 있는 이름을 가진 `struct`가 더 일반적입니다. 예를 들어 `ranges::min_max_result`, `from_chars_result` 등을 참조.
```suggestion
모던 C++에서는 의미 있는 이름을 가진 `struct`가 더 일반적이다. 예를 들어 `ranges::min_max_result`, `from_chars_result` 등을 참조하라.
```

2024-03-16 04:48 UTC, luncliff commented on sections/Functions.md
> +다른 옵션은 `pair`와 `tuple`이 아닌 `optional<T>` 또는 `expected<T, error_code>`를 사용하는 것입니다. 적절하게 사용될 때 이러한 유형은 `pair<T, bool>` 또는 `pair<T, error_code>`보다 멤버들이 무엇을 의미하는지에 대한 더 많은 정보를 전달한다.
```suggestion
다른 옵션은 `pair`와 `tuple`이 아닌 `optional<T>` 또는 `expected<T, error_code>`를 사용하는 것입니다. 적절하게 사용될 때 이러한 타입은 `pair<T, bool>` 또는 `pair<T, error_code>`보다 멤버들의 의도에 대한 더 많은 정보를 전달한다.
```

2024-03-16 04:48 UTC, luncliff commented on sections/Functions.md
> +* 가능하다면 `pair` 또는 `tuple` 반환 유형은 `struct`로 대체되어야 한다. 변형 템플릿에서 `tuple`은 종종 피할 수 없다.
```suggestion
* 가능하다면 `pair` 또는 `tuple` 반환 타입은 `struct`로 대체되어야 한다. 가변 템플릿(variadic templates)에서 `tuple`은 종종 피할 수 없다.
```

2024-03-16 04:48 UTC, luncliff commented on sections/Functions.md
> +* 가능하다면 `pair` 또는 `tuple` 반환 유형은 `struct`로 대체되어야 한다. 변형 템플릿에서 `tuple`은 종종 피할 수 없다.
unavoidable을 직역했다는 느낌을 지우기 위해 아래와 같은 문장을 생각해봤습니다.
```suggestion
* 가능하다면 `pair` 또는 `tuple` 반환 유형은 `struct`로 대체되어야 한다. 변형 템플릿에서는 `tuple`을 사용할 수 밖에 없다.
```

2024-03-16 04:48 UTC, luncliff commented on sections/Functions.md
> +### <a name="Rf-ptr-ref"></a>F.60: "인자가 없을 경우"를 허용한다면 `T&`보다는 `T*`를 선호하라
```suggestion
### <a name="Rf-ptr-ref"></a>F.60: "인자가 없을 경우(no argument)"를 허용한다면 `T&`보다는 `T*`를 선호하라
```

2024-03-16 04:48 UTC, luncliff commented on sections/Functions.md
> +### <a name="Rf-return-const"></a>F.49: `return const T`는 사용하지 말아라
```suggestion
### <a name="Rf-return-const"></a>F.49: `const T`는 함수의 반환 타입으로 사용하지 말아라
```

2024-03-16 04:48 UTC, luncliff commented on sections/Functions.md
> +* `const` 반환 값을 지적한다. `const`를 제거하도록 권한다.
원문: Flag returning a const value. To fix: Remove const to return a non-const value instead.

```suggestion
* `const` 값을 반환에 사용하면 지적한다. `const`를 제거하도록 권한다.
```

2024-03-18 14:59 UTC, utilForever commented
@jabdong4ny @luncliff 님의 리뷰를 반영하고 나시면 저에게 노티해주세요. 2차 리뷰 진행하겠습니다.

2024-03-19 00:23 UTC, jabdong4ny commented
> @jabdong4ny @luncliff 님의 리뷰를 반영하고 나시면 저에게 노티해주세요. 2차 리뷰 진행하겠습니다.

@luncliff 님 comment 확인하였습니다. 2차 리뷰 부탁드립니다.

2024-03-19 02:52 UTC, luncliff approved these changes

2024-03-19 02:52 UTC, luncliff commented on sections/Functions.md
> +* [F.60: "인자가 없을 경우"를 허용한다면 `T&`보다는 `T*`를 선호하라](#Rf-ptr-ref)
https://github.com/CppKorea/CppCoreGuidelines/pull/168/files#r1527088841 에서 제가 놓쳤네요. 이 건 하나만 더 부탁드리겠습니다.
```suggestion
* [F.60: "인자가 없을 경우(no argument)"를 허용한다면 `T&`보다는 `T*`를 선호하라](#Rf-ptr-ref)
```

2024-03-31 15:01 UTC, utilForever requested changes
간단히 살펴봤습니다. 확인 후 수정 부탁드립니다.

2024-03-31 15:01 UTC, utilForever commented on sections/Functions.md
> +일부 사용자 정의 및 표준 라이브러리 타입은 `span<T>`나 반복자와 같이 [복사 비용이 저렴](#Rf-in)하고 값으로 전달될 수 있지만, 변경 가능한(in-out) 참조 의미론(semantics)을 가지고 있다:
```suggestion
일부 사용자 정의 및 표준 라이브러리 타입은 `span<T>`나 반복자처럼 [복사 비용이 저렴](#Rf-in)하고 값으로 전달될 수 있지만, 변경 가능한(in-out) 참조 의미론(semantics)을 가지고 있다:
```

2024-03-31 15:01 UTC, utilForever commented on sections/Functions.md
> +```
```suggestion
```c++
    void increment_all(span<int> a)
    {
        for (auto&& e : a)
            ++e;
    }
```
```

2024-03-31 15:01 UTC, utilForever commented on sections/Functions.md
> +"will-move-from" 매개 변수가 `shared_ptr`이면 [R.34](./References.md/#Rr-sharedptrparam-owner)를 따르고 `shared_ptr`을 값으로 전달한다.
"will-move-from"을 번역하지 않으신 이유가 있나요?

2024-03-31 15:01 UTC, utilForever commented on sections/Functions.md
> +일반적으로 모든 정적 제어 흐름 경로에서 전체 매개변수(또는 `...`을 사용하는 인자묶음(parameter pack))를 정확히 한 번 전달합니다:
```suggestion
일반적으로 모든 정적 제어 흐름 경로에서 전체 매개변수(또는 `...`을 사용하는 인자묶음(parameter pack))를 정확히 한 번 전달한다:
```

2024-03-31 15:01 UTC, utilForever commented on sections/Functions.md
> +* 상속 계층구조에 속한 타입처럼 값 타입이 아닌 경우, 개체를 `unique_ptr` 혹은 `shared_ptr`로 반환하라
```suggestion
* 상속 계층 구조에 속한 타입처럼 값 타입이 아닌 경우, 개체를 `unique_ptr` 혹은 `shared_ptr`로 반환하라.
```

2024-03-31 15:01 UTC, utilForever commented on sections/Functions.md
> +* 많약 값의 이동 비용이 크다면 (`array<BigTrivial>` 같은 경우), 자유 저장소에 할당하고 그 핸들을 (`unique_ptr`와 같은) 반환하는 것을 고려하라. 또는 `const`가 아닌 참조(출력 매개변수)를 전달해 개체를 채워넣도록 하라
```suggestion
* 만약 값의 이동 비용이 크다면 (`array<BigTrivial>` 같은 경우), 자유 저장소에 할당하고 그 핸들을 (`unique_ptr`와 같은) 반환하는 것을 고려하라. 또는 `const`가 아닌 참조(출력 매개변수)를 전달해 개체를 채워넣도록 하라.
```

2024-03-31 15:01 UTC, utilForever commented on sections/Functions.md
> +* 최대 크기(capacity)를 가진 개체(예를 들어 `std::string`, `std::vector`)를 여러 함수 호출과정에서 재사용하고자 한다면, [입출력 매개변수로 참조를 전달하라](#Rf-out-multi).
```suggestion
* 최대 크기(capacity)를 가진 개체(예를 들어 `std::string`, `std::vector`)를 여러 함수 호출 과정에서 재사용하고자 한다면, [입출력 매개변수로 참조를 전달하라](#Rf-out-multi).
```

2024-03-31 15:01 UTC, utilForever commented on sections/Functions.md
> +다른 옵션은 `pair`와 `tuple`이 아닌 `optional<T>` 또는 `expected<T, error_code>`를 사용하는 것입니다. 적절하게 사용될 때 이러한 타입은 `pair<T, bool>` 또는 `pair<T, error_code>`보다 멤버들의 의도에 대한 더 많은 정보를 전달한다.
```suggestion
다른 옵션은 `pair`와 `tuple`이 아닌 `optional<T>` 또는 `expected<T, error_code>`를 사용하는 것이다. 적절하게 사용될 때 이러한 타입은 `pair<T, bool>` 또는 `pair<T, error_code>`보다 멤버들의 의도에 대한 더 많은 정보를 전달한다.
```

2024-03-31 15:01 UTC, utilForever commented on sections/Functions.md
> +반환할 개체가 복사 비용이 많이 드는 로컬 변수에서 초기화되는 경우 명시적인 `move`가 복사를 피하는 데 도움이 될 수 있다:
```suggestion
반환할 개체가 복사 비용이 많이 드는 지역 변수에서 초기화되는 경우 명시적인 `move`가 복사를 피하는 데 도움이 될 수 있다:
```

2024-03-31 15:01 UTC, utilForever commented on sections/Functions.md
> +가능하기는 하지만, C++에서 `nullptr`인 개체를 생성하는 것은 정상적(valid)이지 않다(예를 들어, `T* p = nullptr; T& r = (T&)*p;`). 그런 오류는 굉장히 드물다(very uncommon).
```suggestion
가능하기는 하지만, C++에서 `nullptr`인 개체를 생성하는 것은 정상적(valid)이지 않다 (예를 들어, `T* p = nullptr; T& r = (T&)*p;`). 그런 오류는 굉장히 드물다(very uncommon).
```

2024-03-31 15:01 UTC, utilForever commented on sections/Functions.md
> +`const` 값을 반환하는 것은 추천하지 않는다. 오래된 조언들은 무의미하다; 의미도 없고 이동 의미구조를 방해한다.
```suggestion
`const` 값을 반환하는 것은 추천하지 않는다. 오래된 조언들은 무의미하다; 의미도 없고 이동 의미 구조를 방해한다.
```

2024-03-31 15:01 UTC, utilForever commented on sections/Functions.md
> +전달 인자에 `const`가 사용되면 (매우 자주 발생하는) 이동 의미구조를 막는다.
```suggestion
전달 인자에 `const`가 사용되면 (매우 자주 발생하는) 이동 의미 구조를 막는다.
```

2024-03-31 23:54 UTC, jabdong4ny commented on sections/Functions.md
> +"will-move-from" 매개 변수가 `shared_ptr`이면 [R.34](./References.md/#Rr-sharedptrparam-owner)를 따르고 `shared_ptr`을 값으로 전달한다.
위 내용에 맞춰서 '넘겨주는(will-move-from)'라고 표기했었어야 했는데 누락한 것 같습니다.

2024-04-07 06:24 UTC, jabdong4ny commented on sections/Functions.md
> +"will-move-from" 매개 변수가 `shared_ptr`이면 [R.34](./References.md/#Rr-sharedptrparam-owner)를 따르고 `shared_ptr`을 값으로 전달한다.
@utilForever [sections/Functions.md] 업데이트 하였습니다. (https://github.com/CppKorea/CppCoreGuidelines/pull/168/commits/7c643f064eedb0c470d2faa5468977ff6cefe81d)

2024-05-07 14:51 UTC, luncliff approved these changes
https://github.com/CppKorea/CppCoreGuidelines/pull/168#discussion_r1545710186 의 내용이 반영되어, Resolved 상태라고 생각됩니다.

Assignee인 @twoo0220 님께서 병합해주시면 될 것 같습니다.

2024-05-07 14:53 UTC, merged

2024-05-21 07:21 UTC, utilForever reviewed
제가 너무 늦게 확인했네요. 기여해주셔서 감사합니다. 👍